version: '3.3'


networks:
  main:
    driver: bridge


services:
  test_auth:
    environment:
      APP_TYPE: "${TEST_ENVIRONMENT}"
    build:
      context: .
      dockerfile: ./srv/test/Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - main