version: '3.8'


services:
  app_auth:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - postgresdb
    networks:
      main:
        aliases:
          - app_auth


  postgresdb:
    image: postgres:12.8
    environment:
        POSTGRES_PASSWORD: "${PASSWORD}"
        POSTGRES_USER: "${DB_USER}"
        POSTGRES_DB: "${DB_NAME}"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      main:
        aliases:
          - postgresdb

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app_auth
    networks:
      main:
        aliases:
          - nginx



volumes:
  data:

networks:
  main: