version: '3.3'


networks:
  main:
    driver: bridge


services:
  app_auth:
    restart: always
    build:
      context: .
      dockerfile: ./SRV/app/Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./static/:/static
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - main



  db:
    image: postgres:12.8
    environment:
        POSTGRES_PASSWORD: "${PASSWORD}"
        POSTGRES_USER: "${DB_USER}"
        POSTGRES_DB: "${DB_NAME}"
    volumes:
      - data_ps:/var/lib/postgresql/data_ps/
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - main


  webserver:
    build: ./SRV/webserver
    ports:
      - 1337:80
    depends_on:
      - app_auth
      - db
    volumes:
      - ./SRV/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./SRV/webserver/conf.d/:/etc/nginx/conf.d
      - ./static/:/static
    networks:
      - main

volumes:
  data_ps:
