# Generated by Django 3.2.7 on 2021-10-19 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('temp', 'temp'), ('permanent', 'permanent')], max_length=128)),
                ('destination', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'file_storages',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=300)),
                ('size', models.BigIntegerField()),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='fileservice.filestorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
