# Generated by Django 3.2.7 on 2021-10-12 06:52

from django.db import migrations, models
import src.accounts.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True, validators=[src.accounts.validators.validate_name])),
                ('first_name', models.CharField(max_length=50, validators=[src.accounts.validators.validate_name])),
                ('last_name', models.CharField(max_length=50, validators=[src.accounts.validators.validate_name])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField(null=True, validators=[src.accounts.validators.validate_age])),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
