# Generated by Django 3.2.7 on 2021-09-24 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('b0f1470a-bb1b-4a87-8149-3bdba1ce6a27'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
