# Generated by Django 3.2.7 on 2021-09-24 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b65dbb3-de70-4fb0-bc5e-11e1e76c837e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
