# Generated by Django 3.2.7 on 2021-09-24 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5067269f-c3fe-4b4f-b6ee-bf84c4ccf0d0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
