# Generated by Django 3.2.7 on 2021-09-24 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe02df66-0a00-456d-b0bc-f1814822eab0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
