# Generated by Django 3.2.7 on 2021-09-24 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210924_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c104a247-e465-4949-b928-9a5e2a3ba954'), editable=False, primary_key=True, serialize=False),
        ),
    ]
